"""HTML rendering for the daily brief."""
from __future__ import annotations
import html
from datetime import date, datetime
from typing import List, Dict
from pathlib import Path
from string import Template

TEMPLATE = Template(r"""<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>医疗资讯日报 · $today</title>
<style>
  :root { color-scheme: light dark; }
  * { box-sizing: border-box; }
  body {
    font-family: -apple-system, "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif;
    max-width: 960px; margin: 0 auto; padding: 24px 20px 80px;
    line-height: 1.6; color: #222; background: #fafafa;
  }
  @media (prefers-color-scheme: dark) {
    body { color: #ddd; background: #1a1a1a; }
    a { color: #6bb6ff; }
    .item { background: #252525; }
    .item:hover { background: #2d2d2d; }
    .stat { color: #aaa; }
  }
  h1 { font-size: 1.6em; margin: 0 0 6px; }
  .subhead { color: #666; font-size: 0.9em; margin-bottom: 24px; }
  .stats { display: flex; gap: 18px; flex-wrap: wrap; margin: 18px 0 28px; padding: 14px 18px; background: #fff; border-radius: 8px; border: 1px solid #eee; }
  .stat { font-size: 0.92em; color: #555; }
  .stat strong { color: #c92a2a; font-size: 1.15em; }
  h2 { font-size: 1.2em; margin: 32px 0 12px; padding-bottom: 6px; border-bottom: 2px solid #c92a2a; }
  .item { padding: 12px 16px; margin: 8px 0; background: #fff; border-radius: 6px; border: 1px solid #eee; transition: background 0.1s; }
  .item:hover { background: #f5f5f5; }
  .item-title { font-weight: 500; font-size: 1.02em; }
  .item-title a { text-decoration: none; color: inherit; }
  .item-title a:hover { color: #c92a2a; text-decoration: underline; }
  .item-meta { font-size: 0.82em; color: #888; margin-top: 4px; display: flex; gap: 12px; flex-wrap: wrap; }
  .item-kw { display: inline-block; background: #fff3bf; color: #6b5b00; padding: 1px 8px; border-radius: 3px; font-size: 0.78em; margin-right: 4px; }
  @media (prefers-color-scheme: dark) {
    .item-kw { background: #5a4a00; color: #ffe066; }
  }
  .badge { display: inline-block; padding: 1px 6px; border-radius: 3px; font-size: 0.75em; }
  .badge-new { background: #2b8a3e; color: #fff; }
  .empty { color: #999; font-style: italic; padding: 20px 0; }
  .footer { margin-top: 60px; padding-top: 16px; border-top: 1px solid #eee; color: #999; font-size: 0.8em; text-align: center; }
</style>
</head>
<body>

<h1>医疗资讯日报</h1>
<div class="subhead">$today · 共 $total 条 · 命中关键词 <strong>$matched</strong> 条</div>

<div class="stats">
  <div class="stat">政策类: <strong>$policy_count</strong></div>
  <div class="stat">AI/器械类: <strong>$ai_count</strong></div>
  <div class="stat">数据源: <strong>$src_count</strong></div>
  <div class="stat">生成时间: $generated</div>
</div>

$body

<div class="footer">
  Generated by medical-brief · 数据来源: 政府公开网站 · 仅供个人学习参考
</div>

</body>
</html>
""")


def _esc(s: str) -> str:
    return html.escape(s or "", quote=True)


def _render_item(item: Dict) -> str:
    title = _esc(item["title"])
    url = _esc(item["url"])
    src = _esc(item.get("source_label") or item.get("source_id") or "")
    date = _esc(item.get("publish_date") or "")
    kw_html = "".join(f'<span class="item-kw">{_esc(k)}</span>' for k in item.get("matched_kw", []))
    date_html = f'<span>{date}</span>' if date else ''
    return f"""
<div class="item">
  <div class="item-title"><a href="{url}" target="_blank" rel="noopener">{title}</a></div>
  <div class="item-meta">
    <span>{src}</span>
    {date_html}
    {kw_html}
  </div>
</div>"""


def _render_section(title: str, items: List[Dict], empty_msg: str = "（今日无新增）") -> str:
    if not items:
        return f"<h2>{_esc(title)}</h2><div class='empty'>{empty_msg}</div>"
    body = "\n".join(_render_item(it) for it in items)
    return f"<h2>{_esc(title)}</h2>\n{body}"


def render_html(items: List[Dict], today: str = None) -> str:
    """Render the daily brief HTML.

    items: list of dicts with keys: title, url, source_label, source_id,
           category, publish_date, matched_kw
    """
    if today is None:
        today = date.today().isoformat()

    policy = [it for it in items if it.get("category") == "policy"]
    ai = [it for it in items if it.get("category") == "ai"]
    matched = [it for it in items if it.get("matched_kw")]
    sources = set(it.get("source_label") or it.get("source_id") for it in items)

    body_parts = [
        _render_section("医保 / 政策", policy),
        _render_section("医疗 AI / 创新器械", ai),
    ]
    body = "\n".join(body_parts)

    return TEMPLATE.substitute(
        today=today,
        total=len(items),
        matched=len(matched),
        policy_count=len(policy),
        ai_count=len(ai),
        src_count=len(sources),
        generated=datetime.now().strftime("%H:%M:%S"),
        body=body,
    )


def write_brief(items: List[Dict], out_path: Path, today: str = None) -> Path:
    if today is None:
        today = date.today().isoformat()
    html_str = render_html(items, today)
    out_path.write_text(html_str, encoding="utf-8")
    return out_path
